server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/knowledge_platform?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 1234
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

jwt:
  secret: aW52YWxpZF9rZXlfdGhhdF9tdXN0X2JlX2F0X2xlYXN0XzI1Nl9iaXRzX2xvbmdfZm9yX2hzMjU2
  expire-time: 86400000 # 24 hours

# 支付宝配置
alipay:
  app-id: 9021000163602080
  private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCkQMQidDpXaCzuQklOm0hRp6pBNwxSQQ2dWtE4gZ3U5DC0cb0rDcTL1fL6Qc4CHkhkWD23f2QQ3kRB/izkgWs5+hCtypcUvsROs+2mo64RE9M9EAIfiq7plkDYf7DZWihEJeZeJ0a5mHJt78TznOYwxUnHkqSIzSiFpVrJqa6h64B4EOw+Te66zm9fDqlILuKa49yEifKpFyRclq3567b2KqxCNW0Xr0ZljDQxcWilwiy7UJIYEr9lN7BV2w6FKAJSp3hZ/BA/S31/wauz9wrlGla4Oy2cXvSwCkJiInFy+Oo4jgbcxPMJhrIXzPHhnguVfC3Bcu9dY2DwxN8FUCXzAgMBAAECggEAfxe2K8qvUe7DxV/5BR/WJ4iKjoefuw2nETiyZvy0OYSPwy+25ddzjR1xMv8z/iOcdDhrGM8ziHHTcxTPe8hARc4elbsKh/zMPPGwU56XE5O5gagfXHScvxWJ+3tiRewi+AgzZmsRqI4zDKnYRYAEBXzCh/AJ6+iDEFZQF3Z6L8KifYMMOWKR9AzqQCsc+GI1MOJ9CaEz9IwM1n4XviblCgxt1n9H40n3EWdGlTp3oXmu84o4wIRToVgvBrAkRz3dj6SxZFKlzuIC0scb4e1xi8ThbhK6XfjnSbl3Yda4rIL10DBuRtmLk0P2szdTDoAKLIPRxd2mej24BZZkKgZ2IQKBgQDO/LM/UzpCLhYhDQk+ZEwLLBPxSQrYy40qBLBoFS71NzW7gT7G2+gyoovi+fQ/VibJNMCyLVqD+ZUAAQSrgYtxk/a4okaYJGcAYOP7hl8b4sUWw+ksUx3Vc/uaDM2EKjdi9O2Y1Rzy8xjGPouGspXCsLz11/ov16ztpHcP6jRoCwKBgQDLJZPDsa8A/qfwErAvp+LQOnukiQRmGJ/ZrZMlc6l3W/t0DkSIZSTvA2AnjjaxUqtzSlb9If5FjI0rx0l0AoU6YXy3OzedMTy+ryB+hxp+65p0xm4sIfjapSEJtW5RPA5nB6lc63UPip0VMtAAe8Ld9RVUwnin0OQlegy3oQ6iuQKBgEByE4ky65+xY7h0q50ec0LDPY5RlKv9bH1ZqmctuUomH3e6/QXDcF9blrxb4L1boIXjA+A2GMmgitDOgFq54eXCEP5ZoCs8oklO4YztwG0ZRQ4af14Knu5Xx02mkNKGpmoMInIEYJgQMnV/Acg1kEVm696LmV0OBMyU+XEeFaUTAoGBAJuAOinUOzextu+H/qGcC3yFJ9v8ngdg1guUWEyUyqX5HPPrb/5QHgNvPA1LSQZXV7I6t3ewq6ilO/LE668Htt/He+XuSFXlOLBl8aOo21lIE8VLl03k+06ylCWQYc+A/y1SqgvcmJC69B8j9CBKnBG25wsoiZ87wUgGsvFlMYTRAoGBAJZ31+FCK+uy9DeMtFiZbSgQRMqRI91T/AVrq3p79T+JuW4KiBEmyve6ic2ZWUTxtmscv4jI/nefYcQ9UHmlzrs+2/OkSSUFgZMR/iJjBPYLCY6JgpcXSUNl7g9Q93VejGkAtirvPeyOPUjQE3MaSct8ijGMYGaV678Wrl0yO5RN
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApEDEInQ6V2gs7kJJTptIUaeqQTcMUkENnVrROIGd1OQwtHG9Kw3Ey9Xy+kHOAh5IZFg9t39kEN5EQf4s5IFrOfoQrcqXFL7ETrPtpqOuERPTPRACH4qu6ZZA2H+w2VooRCXmXidGuZhybe/E85zmMMVJx5KkiM0ohaVayamuoeuAeBDsPk3uus5vXw6pSC7imuPchInyqRckXJat+eu29iqsQjVtF69GZYw0MXFopcIsu1CSGBK/ZTewVdsOhSgCUqd4WfwQP0t9f8Grs/cK5RpWuDstnF70sApCYiJxcvjqOI4G3MTzCYayF8zx4Z4LlXwtwXLvXWNg8MTfBVAl8wIDAQAB
  notify-url: http://localhost:8081/user/alipay/notify
  sandbox: true
